spring.application.name=Backend-Project

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://fsse2406-db-jeffery.cpy2u6cwiy8w.ap-southeast-1.rds.amazonaws.com:3306/eCommerce
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/fsse2406-project-jeffery

stripe.apikey=sk_test_51PtLhyBRyDFU5GVJwv8IZTGzo9rctL2v4Raru3j58Cn7GWWjLIsltq70eXiVLlBj4i4EkI5H6qCVSD2UzJ3MUG4d00p1BkHNgI